version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env      # lit MYSQL_USER, MYSQL_PASSWORD, MYSQL_DATABASE…
    environment:
      # surcharge uniquement l’hôte MySQL
      - MYSQL_HOST=db
    depends_on:
      - db
    restart: on-failure
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - ./backend/.env      # ou un .env spécifique pour le DB
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
